### ISSUE TITLE
import error when using git version and python3.5

### ISSUE THREAD

**Issue by thengineer** [timClicks/slate#24]
I have installed the git version using the setup script, and when trying to import slate i get the following error:   

     >>> import slate
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.5/site-packages/slate-0.5.1-py3.5.egg/slate/__init__.py", line 66, in <module>
      File "/usr/local/lib/python3.5/site-packages/slate-0.5.1-py3.5.egg/slate/classes.py", line 25, in <module>
    ImportError: No module named 'utils'

**Comment by pchaigno** [comment]
I have the same issue.
Slate is expecting to find `utils.py` in the current directory, which obviously isn't there.

**Comment by wearpants** [comment]
Can this get merged please?

**Comment by benjaminweb** [comment]
It shouldn't if PR #32 turns out to do the same and more (untested). Read that chronology.

**Comment by arderyp** [comment]
this error persists, over 3 years later.  I guess its impossible to run slate on python 3?

**Comment by juicedatom** [comment]
+1 on the above.  I was able to manually patch with the above fix.
