### ISSUE TITLE
Getting Assert Error on every PDF

### ISSUE THREAD

**Issue by sof123** [timClicks/slate#35]
Hey just trying to get started with slate using the tutorial and getting this error. I've tried with 3 pdfs now. Here's the code:

`import slate
with open('testpdf3.pdf') as f:
	print type(f)
	doc = slate.PDF(f)`

And the stack trace:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    doc = slate.PDF(f)
  File "C:\Users\S\Anaconda2\lib\site-packages\slate\slate.py", line 38, in __init__
    self.doc.set_parser(self.parser)
  File "C:\Users\S\Anaconda2\lib\site-packages\pdfminer\pdfparser.py", line 318, in set_parser
    self.xrefs = parser.read_xref()
  File "C:\Users\S\Anaconda2\lib\site-packages\pdfminer\pdfparser.py", line 747, in read_xref
    self.read_xref_from(pos, xrefs)
  File "C:\Users\S\Anaconda2\lib\site-packages\pdfminer\pdfparser.py", line 727, in read_xref_from
    xref.load(self, debug=self.debug)
  File "C:\Users\S\Anaconda2\lib\site-packages\pdfminer\pdfparser.py", line 99, in load
    self.load_trailer(parser)
  File "C:\Users\S\Anaconda2\lib\site-packages\pdfminer\pdfparser.py", line 107, in load_trailer
    assert kwd is self.KEYWORD_TRAILER
AssertionError

**Comment by TG0** [comment]
Try:

with open('testpdf3.pdf', 'rb') as f:
