### ISSUE TITLE
Import Issue for pdfminer (python 2.7)

### ISSUE THREAD

**Issue by ameyamahajan** [timClicks/slate#37]
I am using this tool for converting some of my pdf files into a bare text file. I encountered the following issue.

`>>> import slate 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ameya/anaconda/envs/webapp_pandas/lib/python2.7/site-packages/slate/__init__.py", line 48, in <module>
    from slate import PDF
  File "/Users/ameya/anaconda/envs/webapp_pandas/lib/python2.7/site-packages/slate/slate.py", line 3, in <module>
    from pdfminer.pdfparser import PDFParser, PDFDocument
ImportError: cannot import name PDFDocument
>>> with open(' SOME FILE NAME ') as fd:
...     doc = slate.PDF(fd)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'slate' is not defined`

I fixed it by downgrading the pdfminer to 20110515 version. 
_Successfully uninstalled pdfminer-20140328
Successfully installed pdfminer-20110515_

I guess the issue of import occurs in following the piece of code:
[classes.py](https://github.com/timClicks/slate/blob/master/src/slate/classes.py#L17-L20
)

**Comment by jangdan** [comment]
perhaps related to #6?
