### ISSUE TITLE
Install error using python 3

### ISSUE THREAD

**Issue by brianbruggeman** [timClicks/slate#38]
```
$ pip install slate
Collecting slate
  Downloading slate-0.3.zip
Collecting distribute (from slate)
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r9/kv1j05355r34570x2f5wpxpr0000gn/T/pip-build-l23narcj/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/r9/kv1j05355r34570x2f5wpxpr0000gn/T/pip-build-l23narcj/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/r9/kv1j05355r34570x2f5wpxpr0000gn/T/pip-build-l23narcj/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/r9/kv1j05355r34570x2f5wpxpr0000gn/T/pip-build-l23narcj/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/r9/kv1j05355r34570x2f5wpxpr0000gn/T/pip-build-l23narcj/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/r9/kv1j05355r34570x2f5wpxpr0000gn/T/pip-build-l23narcj/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/r9/kv1j05355r34570x2f5wpxpr0000gn/T/pip-build-l23narcj/distribute/](url)
```

**Comment by mjkaufer** [comment]
Bump

**Comment by Bouni** [comment]
Same problem here, Python 3.6.2 on Arch linux

**Comment by karolpiczak** [comment]
Bumped into this too. Seems like it was fixed in 0a0a4a739928e21f782c02d1fd4bee4d496df325, but I couldn't get it from PyPI directly yet.

`pip install https://github.com/timClicks/slate/archive/master.zip` did the job though.

**Comment by NicolaiLolansen** [comment]
Thank you @karoldvl !

**Comment by gnfrazier** [comment]
Came here to report the above bug when using pip install in anaconda on linux.

Thank you @karoldvl and @brianbruggeman for solution and reporting.

**Comment by fritzmark** [comment]
Still the same here. It seems pipy is not up to date.

**Comment by akiori** [comment]
thanks for @karoldvl 's solution, but there exist `AttributeError: module 'slate' has no attribute 'pdf'`...

**Comment by yongduek** [comment]
The same error.

Python 3.7.1rc1 (v3.7.1rc1:2064bcf6ce, Sep 26 2018, 15:15:36) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import slate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\VIP\AppData\Local\Programs\Python\Python37\lib\site-packages\slate\__init__.py", line 66, in <module>
    from .classes import PDF
  File "C:\Users\VIP\AppData\Local\Programs\Python\Python37\lib\site-packages\slate\classes.py", line 25, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'

**Comment by ronalddas** [comment]
@yongduek . Hi, even I am getting the same error, no module named utils

**Comment by mwburgoyne** [comment]
Getting the same problem as well (ModuleNotFoundError: No module named 'utils')
pdfminer.__version__ is 20181108

Slate version installed is slate-0.5.2, this was installed via pip install https://github.com/timClicks/slate/archive/master.zip (as suggested at https://github.com/timClicks/slate/issues/38) in order to solve the error message
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

**Comment by rishikesh67** [comment]
👍 I am also getting the same error as reported in the very top of this discussion.

> I tried with `Python 2` and `Python 3` both.

```bash
>>> import os
>>> 
>>> os.system("pip3.6 install slate")
Collecting slate
  Using cached https://files.pythonhosted.org/packages/40/cc/ee9faa3ca14cfc1c5c76305a62b8da84d3ae5abf6cf8c89045a1d48f86ce/slate-0.3.zip
Collecting distribute (from slate)
  Using cached https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_h/d17s0sg11q74f68sxqnvg1nm0000gn/T/pip-install-lc39nysg/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/_h/d17s0sg11q74f68sxqnvg1nm0000gn/T/pip-install-lc39nysg/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/_h/d17s0sg11q74f68sxqnvg1nm0000gn/T/pip-install-lc39nysg/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/_h/d17s0sg11q74f68sxqnvg1nm0000gn/T/pip-install-lc39nysg/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/_h/d17s0sg11q74f68sxqnvg1nm0000gn/T/pip-install-lc39nysg/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/_h/d17s0sg11q74f68sxqnvg1nm0000gn/T/pip-install-lc39nysg/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_h/d17s0sg11q74f68sxqnvg1nm0000gn/T/pip-install-lc39nysg/distribute/
256
>>> 
``` 

💯 Can someone please suggest the fix if anyone of you guys have fixed already. Maybe some versions may work. I tried it on **MAC OS X Mojave 10.14.4** .

**Comment by Hiteshm01** [comment]
@rishikesh67 this works for most https://github.com/timClicks/slate/issues/38#issuecomment-331671305!
