### ISSUE TITLE
AttributeError: module 'slate' has no attribute 'PDF'

### ISSUE THREAD

**Issue by Wesalius** [timClicks/slate#42]
```
filename = "file.pdf"
import slate
with open('file.pdf') as f:
    doc = slate.PDF(f)
    print(doc)
```
gives
```
Traceback (most recent call last):
  File "C:\Users\.....\Desktop\interna\slate\slate.py", line 2, in <module>
    import slate
  File "C:\Users\.....\Desktop\interna\slate\slate.py", line 4, in <module>
    doc = slate.PDF(f)
AttributeError: module 'slate' has no attribute 'PDF'
```

running Python 3.6.4, installed the latest slate downloaded from github today

**Comment by jangdan** [comment]
A possible solution for many problems; this worked for me a few months ago, with Python 3.6.4: https://github.com/timClicks/slate/pull/32#issuecomment-365474036
