### ISSUE TITLE
PDFDocument() from pdfminer requires a parser argument

### ISSUE THREAD

**Issue by kehayakawa** [timClicks/slate#43]
Using the fix from #24 and python 3.5.2, I call slate.PDF(file) but PDFDocument requires a parser. What should be put here? I tried self.parser but this didn't work.

Traceback (most recent call last):
  File "pdftotext.py", line 7, in <module>
    doc = slate.PDF(f)
  File "//anaconda/lib/python3.5/site-packages/slate/classes.py", line 56, in __init__
    self.doc = PDFDocument()
TypeError: __init__() missing 1 required positional argument: 'parser'

putting self.doc = PDFDocument(self.parser) leads to this error that I cannot fix either.

Traceback (most recent call last):
  File "pdftotext.py", line 7, in <module>
    doc = slate.PDF(f)
  File "//anaconda/lib/python3.5/site-packages/slate/classes.py", line 57, in __init__
    self.doc = PDFDocument(self.parser)
  File "//anaconda/lib/python3.5/site-packages/pdfminer/pdfdocument.py", line 559, in __init__
    pos = self.find_xref(parser)
  File "//anaconda/lib/python3.5/site-packages/pdfminer/pdfdocument.py", line 773, in find_xref
    for line in parser.revreadlines():
  File "//anaconda/lib/python3.5/site-packages/pdfminer/psparser.py", line 285, in revreadlines
    s = self.fp.read(prevpos-pos)
  File "//anaconda/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 2: invalid start byte

**Comment by fawcao** [comment]
I've got a same error.

doc = PDF(file)
  File "\\Miniconda3\lib\site-packages\slate-0.5.2-py3.6.egg\slate\classes.py", line 56, in __init__
TypeError: __init__() missing 1 required positional argument: '**parser**'

**Comment by fhightower** [comment]
In the original issue, @kehayakawa raises two issues regarding the use of this package in python3.x. Thus, there are two steps for preparing this package for use in python3.x.

### Step One

First, to get this package working in python3.x you will need to change the line of the [/src/slate/classes.py](https://github.com/timClicks/slate/blob/d91b5a6d7848815972273f3c31fa82b6b605d272/src/slate/classes.py#L56) that reads:

```
self.doc = PDFDocument()
```
to 
```
self.doc = PDFDocument(self.parser)
```

### Step Two

Second, when using the slate package you need to read the file as bytes:

```python
with open('example.pdf', 'rb') as f:
    doc = slate.PDF(f)
```

Notice I replaced `open('example.pdf')` with `open('example.pdf', 'rb')`. This should fix the problem.

When you do this, you are telling python to read the file (`r`) in binary mode (`b`) (you can read more on how the `open` function works here: https://docs.python.org/3.3/library/functions.html#open).

**Comment by Luotharx** [comment]
@fhightower Sorry, I can't fix the problem by the way. It still required positional argument:'parser'. Is there any other way to solve it? Thanks!

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-1cba3371ef50> in <module>
      1 with open('example.pdf','rb') as f:
----> 2     doc = slate.PDF(f)
      3 
      4 doc

e:\ProgramData\Anaconda3\lib\site-packages\slate\classes.py in __init__(self, file, password, just_text, check_extractable, char_margin, line_margin, word_margin)

TypeError: __init__() missing 1 required positional argument: 'parser'

**Comment by fhightower** [comment]
@Luotharx : Sorry about that; my original comment was a bit ambiguous. I've updated it to be more clear. For a solution to the problem you are running into, look at the "Step One" section of my original comment (https://github.com/timClicks/slate/issues/43#issuecomment-427564672)

**Comment by Vinod-Kumar-G** [comment]
> ### Step One
> First, to get this package working in python3.x you will need to change the line of the [/src/slate/classes.py](https://github.com/timClicks/slate/blob/d91b5a6d7848815972273f3c31fa82b6b605d272/src/slate/classes.py#L56) that reads:
> 
> ```
> self.doc = PDFDocument()
> ```
> 
> to
> 
> ```
> self.doc = PDFDocument(self.parser)
> ```
> 
> ### Step Two
> Second, when using the slate package you need to read the file as bytes:
> 
> ```python
> with open('example.pdf', 'rb') as f:
>     doc = slate.PDF(f)
> ```
> 


This didn't worked for me 👎 

<ipython-input-2-3ee2c9b59b88> in get_pdf_text(file_path)
     64 def get_pdf_text(file_path):
     65     with open(file_path,'rb') as f:
---> 66         extracted_text = slate3k.PDF(f)
     67     return extracted_text.text()
     68 

~\Anaconda3\envs\rstudio\lib\site-packages\slate3k\classes.py in __init__(self, file, password, just_text, check_extractable, char_margin, line_margin, word_margin)
     57 
     58         if PYTHON_3:
---> 59             self.doc = PDFDocument(self.parser)
     60             self.parser.set_document(self.doc)
     61             self.doc.set_parser(self.parser)

TypeError: __init__() missing 1 required positional argument: 'parser'

**Comment by fhightower** [comment]
Ah, ok. Sorry to hear that. I tried to replicate the issue you reported @Vinod-Kumar-G, but ran into some other problems, so... as this package (slate) clearly isn't supported, I'm not going to try to debug it any further. Sorry :(

**Comment by devamsheth0806** [comment]
I was also stuck in this problem...
And as previous;y mentioned by @fhightower in the comment [#43](https://github.com/timClicks/slate/issues/43#issuecomment-427564672)
I also tried that, but it also didn't worked for me.

but when I saw the file [/src/slate/classes.py](https://github.com/timClicks/slate/blob/d91b5a6d7848815972273f3c31fa82b6b605d272/src/slate/classes.py) carefully, I just added 'not' before PYTHON_3 in if condition.

`if not PYTHON_3:`

in line number 55 and 69, then it worked for me.

**Comment by nina7045** [comment]
Good idea! After adding the 'not' it now works for me as well. Thank you!

**Comment by manjeetkaur2195** [comment]
Yes , worked for me as well . Thanks for the solution
