### ISSUE TITLE
AttributeError when opening documents that contain chinese characters

### ISSUE THREAD

**Issue by Alexander-0x80** [timClicks/slate#7]
When opening documents that contain chinese/thai characters i get an exception saying : 

``` python
File "create_index.py", line 16, in <module>
    pdf_data = slate.PDF(f)
  File "/home/alexander/dev/pdf_indexer/env/local/lib/python2.7/site-packages/slate/slate.py", line 49, in __init__
    self._cleanup()
  File "/home/alexander/dev/pdf_indexer/env/local/lib/python2.7/site-packages/slate/slate.py", line 57, in _cleanup
    del self.device
AttributeError: device
```

**Comment by bsmartt13** [comment]
I'm seeing this with this PDF: .  However the only version of pdfminer/slate that I've gotten to work is 
slate==0.3
pdfminer==20110515 
so please keep that in mind..

```
Traceback (most recent call last):
...
    doc = slate.PDF(read_handle)
  File "/Users/bsmartt/reputation_env/lib/python2.7/site-packages/slate/slate.py", line 49, in __init__
    self._cleanup()
  File "/Users/bsmartt/reputation_env/lib/python2.7/site-packages/slate/slate.py", line 57, in _cleanup
    del self.device
AttributeError: device
```

Happens with this pdf: http://www.emc.com/collateral/white-papers/h12756-wp-shell-crew.pdf

At a glance I didn't notice any chinese/thai, but there are definitely some funky characters in there.

**Comment by bsmartt13** [comment]
However, it would be awesome to not fail out like this.  I'm in a position where it would be awesome if I could recover (catch) this as a different exception (so as to be certain it was due to password protection), I could notify the user 'hey, the pdf you gave us is password protected, and we do not currently support XYZ from password protected PDFs'.

**Comment by timClicks** [comment]
@bsmartt13 hey sorry I've taken months to get back to you, issuing some kind of useful if we encounter a PDF that expects a password seems very useful.
